str=("  Hello, Python! ")
print(len(str))
print(str.lower( ))
print(str.upper( ))
print(str.replace("Hello","world"))
print(str.find("P"))
print(str.split(","))
print(str.isdigit())

num=(3,-5,7,2)
print(abs(-5))
print(max(num))
print(min(num))
print(round(5.678))
