let1=("Job")
let2=("thomas")
let3=(let1+" "+let2)
print(let3)
print(let3[0:2])
print(let3.upper())
print(let3.lower())
print(let3.split())
print(let3.replace("Job","JOB"))
message=("he said that \"he can cook food\".")
print(message)